# .github/workflows/publish.yml
name: Publish Package

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Build
      run: ./gradlew build

    - name: Test
      run: ./gradlew test

  publish:
    needs: build_and_test
    runs-on: ubuntu-latest
    env:
      GITHUB_USERNAME: ${{ github.actor }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Set version
      run: printf "\nversion=1.$(git rev-list --count HEAD)" >> gradle.properties

    - name: Publish package
      run: ./gradlew publish