# .github/workflows/build.yml
name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Build
      run: ./gradlew build
