name: Protolint

on: [push, pull_request]

jobs:
  protolint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.0

    - name: Install protolint
      run: go get -u github.com/yoheimuta/protolint/cmd/protolint

    - name: Run protolint
      run: protolint lint src/**/*.proto